services: 
  postgres:
    image: postgres:latest
    container_name: postgres_container
    ports:
      - "5433:5432"
    environment: 
      POSTGRES_USER: postgres_user
      POSTGRES_PASSWORD: postgres_password
      POSTGRES_DB: zytologueDB
    
